### ISSUE TITLE
Design review

### ISSUE THREAD

**Issue by johngruen** [mozilla/email-tabs#109]

**Comment by ianb** [comment]
Here's a list of all the UI I can think of:

- [ ] The toolbar icon
- [ ] The popup with the tab list
- [ ] What happens when you open up the tab list while you are on an unselectable page (e.g., about:preferences)
- [ ] Button states when you have something selected, or nothing selected
- [ ] Feedback link
- [ ] Scroll behavior when you have many tabs
- [ ] Notification behavior (or lack thereof) when you copy
- [ ] The error message when you attempt to use Email Tabs and you haven't logged into Gmail
- [ ] The error message on the popup that sticks around
- [ ] The error behavior when you are offline and try to send an email
- [ ] The template selector
- [ ] The loading interstitial (when gmail is slow to load, or when you have a tab that is slow to collect information from)
- [ ] The email templates:
  - [ ] The links-only email template
  - [ ] The screenshot email template
  - [ ] The full article email template
- [ ] After you send your email, the messaging and buttons (close tab, close all tabs)

**Comment by johngruen** [comment]
Notification = push notification 
```
Title: ${experiment.name}
Content: Links to all ${n} tabs copied to your clipboard
```

**Comment by youwenliang** [comment]
> * [ ]  The error message on the popup that sticks around

I don't understand this one, can you explain a bit? thanks

**Comment by youwenliang** [comment]
> Here's a list of all the UI I can think of:
> 
> * [ ]  The toolbar icon

Some ideas for the toolbar icon (including the original one)
![image](https://user-images.githubusercontent.com/8919308/45992142-bea90c80-c0ba-11e8-9048-d5f7be592d63.png)

**Comment by youwenliang** [comment]
> * [ ]  Email subject (for one or many links)

For one tab:
-> Email Tabs: "This is the tab title..."

For multiple tabs:
-> Email Tabs: "This is the tab title..." and # other tabs

Just thought having a same beginning would be easier for users to recognize in their inbox.

**Comment by youwenliang** [comment]
> * [ ]  The email templates:
>   
>   * [ ]  The links-only email template
>   * [ ]  The screenshot email template
>   * [ ]  The full article email template (note #121)

@johngruen Can we use what Sevaan had for the email templates? This: https://mozilla.invisionapp.com/share/N7M35PKUQMY#/screens/305900298_EmailTabs
I can create a new spec based on his design.

**Comment by youwenliang** [comment]
UX Spec (WIP) for most of the UI mentioned above:
https://mozilla.invisionapp.com/share/N7M35PKUQMY

**Comment by johngruen** [comment]
@youwenliang per your earlier question there is an error message if the user is not logged into gmail, the next time you go to the email tabs bar, you see that message.

**Comment by youwenliang** [comment]
Here's the svg for the email tabs icon
https://www.dropbox.com/s/wouq55szsa3gw0q/emailtabs.svg?dl=0
