### ISSUE TITLE
The "This page is asking you to confirm that you want to leave" notification is displayed inconstantly if choosing the "Cancel" option from the "Select an email template" page

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/email-tabs#191]
**[Affected versions]:**
- Firefox 62.0.3 and above

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Email Tabs" add-on (0.1.6967) custom built.
- You are logged in to Gmail.
- Have a website opened in the browser.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Email-Tabs" toolbar button.
3. Click the "Email Tabs" button.
4. Click the "Cancel" button.
5. Repeat steps 2 -> 4 a few times and observe the behavior.

**[Expected result]:**
- The "This page is asking you to confirm that you want to leave" notification is displayed each time when the "Cancel" button is clicked.
OR
- The "This page is asking you to confirm that you want to leave" notification is not displayed when the "Cancel" button is clicked.

**[Actual result]:**
- The "This page is asking you to confirm that you want to leave" notification is displayed inconstantly.

**[Notes]:**
- Attached is a screen recording of the issue: 
![leave](https://user-images.githubusercontent.com/40061643/47140398-c8dbb680-d2c6-11e8-9968-dc29c667cdca.gif)

**Comment by ianb** [comment]
This happens sometimes because the compose window is loading in the background. If you click Cancel slowly, the compose window will have fully loaded, and then you'll get the confirmation message.

Really we don't ever want the confirmation message at this stage, as the user hasn't really changed anything at this stage. So an ideal fix would suppress the confirmation message when you hit Cancel (but shouldn't suppress the confirmation message later, once real composition has begun).

**Comment by ianb** [comment]
I was hoping there would be a good way to suppress the confirmation message, but I haven't found any good way to do this. I'm going to close, since I think we'll just have to accept this inconsistent behavior.
